### PR TITLE
Feature color dict

### PR DESCRIPTION
**Pull request by KT12**
Refactored table_color function into a dict of tuples.  This will be more performant and also make it easier to add additional color schemes in the future.
Refactored handling of empty DataFrame to return `''`.  Prior behavior resulted in output of `</p>`.  It is debatable whether an empty string or throwing an exception would be better if the DataFrame were empty.

### CODE REVIEW

**Comment by KT12** [comment]
I thought a bit more about the empty DataFrame, since #7 referred to it, but it would probably be best to mirror the output of `.to_html()` in pandas.
Currently, using the `.to_html()` method returns an empty table with only the column headers.

**Comment by sbi-rviot** [comment]
Hello @KT12 !
Thank you for your contribution.
I will test it locally and merge your pull request if everything works fine!
It is indeed a nicer approach.
Will come back to you on this very soon.

**Comment by sbi-rviot** [comment]
@KT12 
Super input!

reviewed => merged => deployed

Thanks!

**Comment by KT12** [comment]
Thank you, does merging the PR update the package hosted by PyPA?

**Comment by sbi-rviot** [comment]
Not yet.
There were actually errors (quite a bit) so I had to revert what you did.
It is my fault, I should have done more than a review.
Thankfully one of the user quickly saw this error and communicated with me about it.
It should be all good now.

**Comment by KT12** [comment]
Sorry for the mistakes, and thank you.

**Pull request merged**
